apiVersion: v1
kind: Secret
metadata:
  name: devnotes-secrets
  namespace: devnotes
type: Opaque
stringData:
  mongodb-root-username: admin
  mongodb-root-password: admin
  mongodb-uri: "mongodb://admin:admin@devnotes-mongodb-svc:27017/devnotes?authSource=admin&directConnection=true"