apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devnotes-api-hpa
  namespace: devnotes
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devnotes-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devnotes-web-hpa
  namespace: devnotes
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devnotes-web
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70